#In this script it is important to set the RepositoryUrl in the *.csproj file

name: NuGet Generation for DoenaSoft.AbstractionLayer

on:
  push:
    branches:
      - master
  workflow_dispatch:
      
env:
  SOURCE_URL: https://api.nuget.org/v3/index.json
  SOLUTION_FILE: AbstractionLayer.sln
  PROJECT_FILE: AbstractionLayer.csproj
  PROJECT_FOLDER: AbstractionLayer
  NUGET_SPEC: AbstractionLayer.nuspec
  BUILD_CONFIGURATION: Release
  
jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          source-url: ${{env.SOURCE_URL}}  
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - name: Build AnyCPU
        run: dotnet build ${{ env.PROJECT_FOLDER }}/${{ env.PROJECT_FILE }} -c=Release --no-incremental /p:Platform=AnyCPU

      - name: Pack
        run: dotnet pack ${{ env.PROJECT_FOLDER }}/${{ env.PROJECT_FILE }} --no-build -c=Release -o=./${{ env.PROJECT_FOLDER }}/
          
      - name: Push generated package to Nuget.org
        run: dotnet nuget push ${{ env.PROJECT_FOLDER }}/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "${{env.SOURCE_URL}}" --skip-duplicate
